### PR TITLE
Redesign-Header

### PR DESCRIPTION
**Pull request by TUgonna**
#### What does this PR do?
Re-designs Header

#### Description of Task to be completed?
Re-design Header

#### How should this be manually tested?
Clone the Repo and test that the features work; scripts especially with:
yarn install (For installation of dependencies)
yarn start (To fire up webpack server)

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#152350573](https://www.pivotaltracker.com/n/projects/2091604/stories/152350573)
#### Screenshots (if appropriate)
screen shot 2017-10-27 at 15 49 23
screen shot 2017-10-27 at 15 49 12

#### Questions:
N/A

### CODE REVIEW

**Comment by omorilewa** [comment]
@TUgonna Is it possible to have the logo, menu buttons and sign in/sign up button be on the same line on the web version?

**Comment by TUgonna** [comment]
@omorilewa It is possible. However, because of the width of the logo, that means the menu buttons will be in the middle and I think it would look too cluttered.

**Comment by fisayomi** [comment]
In that case, can the logo be resized @TUgonna ?

**Comment by omorilewa** [comment]
Additionally, we can remove home and/or about from the menu list.

**Comment by TUgonna** [comment]
@fisayomi Resizing the logo to anything smaller will render it unreadable

**Comment by TUgonna** [comment]
@omorilewa If we remove Home, when a user navigates to the contact or careers page. How will the find their way back to the homepage? 

P.S. Not everyone knows that you click the logo to get to the homepage

**Comment by fisayomi** [comment]
There are some errors on the console. Can this be looked into? 
Also, I tried viewing the mobile version but still displays as main.

**Comment by TUgonna** [comment]
@fisayomi If you are using chrome mobile view, I noticed chrome mobile view doesn't show the accurate thing, even in other projects, not just this one. you have to resize your browser manually itself

**Pull request closed without merging**
